;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        kill-region
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-self-insert-command
        org-yank
        sp-beginning-of-sexp
        sp-end-of-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        ace-jump-done
        ace-jump-move
        ace-mc-add-char
        ace-mc-add-multiple-cursors
        ace-mc-add-single-cursor
        ace-mc-do-keyboard-reset
        ace-mc-quick-exchange
        ))
